export const CHANGE_EXCHANGE_VALUE_RATE = "CHANGE_EXCHANGE_VALUE_RATE";
export const ADD_NEW_TRANSACTION_SUCCESS = "ADD_NEW_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const GET_THE_BIGGEST_TRANSACTION = "GET_THE_BIGGEST_TRANSACTION";
export const GET_SUM_OF_TRANSACTIONS = "GET_SUM_OF_TRANSACTIONS";